// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU1STof88Bo9Q5yOBlqzyL9t6vrVXyL6w',
    appId: '1:1068637198083:web:9597e62c6485ccdbb93b36',
    messagingSenderId: '1068637198083',
    projectId: 'dishly-32636',
    authDomain: 'dishly-32636.firebaseapp.com',
    storageBucket: 'dishly-32636.firebasestorage.app',
    measurementId: 'G-QPY6PFGW5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsAqyaE41Qmz9eeGEgh4JTWV3GjsI8AAg',
    appId: '1:1068637198083:android:376331dc9aa66313b93b36',
    messagingSenderId: '1068637198083',
    projectId: 'dishly-32636',
    storageBucket: 'dishly-32636.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmmWSiSfr6GBKr6GpQ1n4I9h5dYF_Pgp0',
    appId: '1:1068637198083:ios:5e375cda8ec73d4bb93b36',
    messagingSenderId: '1068637198083',
    projectId: 'dishly-32636',
    storageBucket: 'dishly-32636.firebasestorage.app',
    iosBundleId: 'com.example.dishly',
  );
}
